apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: bierohero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: wojogu/mcce24-secpv-notification-service:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@notification-db.bierohero:5432/notification
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: bierohero
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
