apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bierohero
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: order
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: bierohero
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
