apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bierohero
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: wojogu/mcce24-secpv-order-service:1.1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@order-db/order
---
apiVersion: v1
kind: Service
metadata:
  namespace: bierohero
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: bierohero
  labels:
    app: order-service