apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: bierohero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: wojogu/mcce24-secpv-payment-service:1.0
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bhconfig
              key: POSTGRES_DB_PAYMENT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bhsecrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bhsecrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@payment-db.bierohero:5432/payment"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bierohero
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: bierohero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bhconfig
              key: POSTGRES_DB_PAYMENT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bhsecrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bhsecrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@payment-db.bierohero:5432/payment"
      volumes:
      - name: tls-secret
        secret:
          secretName: all-tls
      - name: postgres-data
        emptyDir: {}
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: bierohero
spec:
  selector:
    app: payment-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
