apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: bierohero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: wojogu/mcce24-secpv-payment-service:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@payment-db.bierohero:5432/payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bierohero
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
